### ISSUE TITLE
chat

### ISSUE THREAD

**Issue by chen5sj** [wonderobo/saasforce-chatIssue#1]
- [ ] 1.图片不能显示

 ![image](https://user-images.githubusercontent.com/116692247/210769303-31840335-abba-47fe-ac7a-6416c9eba148.png)

**Comment by chen5sj** [comment]
- [ ] 2.txt文件无法成功发送，打开。
- [ ] 3.文本无法换行。

![image](https://user-images.githubusercontent.com/116692247/210769795-29f17d51-b660-4417-8708-afe9c4ba4580.png)

**Comment by chen5sj** [comment]
- [ ] 4.手机端收不到对方发送的消息。

![d8e172d569ea00c7751f4456e7fa479](https://user-images.githubusercontent.com/116692247/210771869-671e36b6-4c69-4851-bebe-c90e005a4205.jpg)
![image](https://user-images.githubusercontent.com/116692247/210772228-e3ec73a5-4676-4f53-89d4-0b773ba7d0bf.png)

**Comment by chen5sj** [comment]
- [ ] 5.收到的视频无法下载。
![image](https://user-images.githubusercontent.com/116692247/210772901-49bdb00b-24ab-43c0-9c53-befa2b10f892.png)

**Comment by chen5sj** [comment]
- [ ] 6.收到的视频无法在线播放。
![image](https://user-images.githubusercontent.com/116692247/210773064-57f9e80f-40a9-44b9-ab43-d0b469fdde5f.png)

**Comment by chen5sj** [comment]
- [ ] 7.位置分享无法显示。
![image](https://user-images.githubusercontent.com/116692247/210774457-175aaca5-63e8-400c-ad46-22290f6c3f2e.png)

**Comment by chen5sj** [comment]
- [ ] 8. Excel，Word，PPT，PDF文件都无法成功收到。
![04fd9042f523c7aa812903434f79327](https://user-images.githubusercontent.com/116692247/210776640-83a744d6-8cac-46b7-b722-70148ea01641.png)

**Comment by chen5sj** [comment]
- [ ] 9.引用时，能显示被引用的内容，但是发送后未显示。

![image](https://user-images.githubusercontent.com/116692247/210777916-733ec2d5-c0bb-45fd-a5e8-02313fe5c175.png)
![image](https://user-images.githubusercontent.com/116692247/210777947-f1c4f6c8-2073-42b9-b56f-e87660efe940.png)

**Comment by chen5sj** [comment]
- [ ] 10.聊天记录的检索功能失效。

![image](https://user-images.githubusercontent.com/116692247/210778530-7be7752c-6d72-4121-a350-4d2f0a17a28d.png)

**Comment by chen5sj** [comment]
- [ ] 11. 已读的消息仍旧显示未读。
![cbec80389490ed48a938ad7e8b5a059](https://user-images.githubusercontent.com/116692247/210779232-763a1655-8060-4d8c-8af5-77e527147be2.png)

**Comment by chen5sj** [comment]
- [ ] 12.使用鼠标右键的粘贴后，发送按钮不亮。
![image](https://user-images.githubusercontent.com/116692247/210779728-21493871-b3b1-425a-ad49-eb4ec91f97d4.png)

**Comment by chen5sj** [comment]
- [ ] 13.语音不能播放。
![image](https://user-images.githubusercontent.com/116692247/210780050-c07048ba-2d58-4892-bb59-5c2b1b7216f3.png)

**Comment by sasf2004** [comment]
> 

已解决

**Comment by sasf2004** [comment]
1-3 已解决

**Comment by sasf2004** [comment]
#13 无法解决 组件原生问题 可参照 http://june000.gitee.io/lemon-im/

**Comment by chen5sj** [comment]
> * [ ]  1.图片不能显示
> 
> ![image](https://user-images.githubusercontent.com/116692247/210769303-31840335-abba-47fe-ac7a-6416c9eba148.png)

2023.1.13 回答：聊天时发送图片已经能正常显示。

**Comment by chen5sj** [comment]
> * [ ]  1.图片不能显示
> 
> ![image](https://user-images.githubusercontent.com/116692247/210769303-31840335-abba-47fe-ac7a-6416c9eba148.png)
